site_name: SDO Analysis Toolkit

# Custom theming
theme:
  name: material #mkdocs #readthedocs #material
  palette:
    - scheme: default
      primary: black
      accent: red
     # Secondary Mode? 
    - scheme: iceberg
      primary: white #indigo
      accent: red
      # Primary mode?

      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: rockwell #Roboto
    code: courier #Roboto Mono


# External plugins for material for mkdocs --> We using this for mermaid
plugins:
- search
- mermaid2



# Whatever type of fancy decorators we want for the markdown rendering
markdown_extensions:
  - attr_list
  - pymdownx.betterem
  - abbr 
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

use_directory_urls: false

# Put lists here that you want to show up on the navigation screen. 
# If you want them to show up on the landing page, then they should be added on the index.md file
nav: 
- Home: index.md
- Installation: installation/overview.md
- Analysis: analysis/overview.md
- Custom Classes: classes/overview.md
