% Constructor for the Error Structure 

function errorStruct = errorStruct_new(N_FIELDS)
    %// Precast empty
errorStruct= struct( ...
    'fieldname',                cell(1,N_FIELDS), ...
    'reference',                cell(1,N_FIELDS), ...
    'x0States',                 cell(1,N_FIELDS), ...
    'dof_px_correct',           cell(1,N_FIELDS), ...
    'predicted_px',             cell(1,N_FIELDS), ...
    'L0_running',               cell(1,N_FIELDS), ...
    'L1_running',               cell(1,N_FIELDS), ...
    'L2_running',               cell(1,N_FIELDS), ...
    'L_inf',                    cell(1,N_FIELDS), ...
    'L0_running_x_state',       cell(1,N_FIELDS), ...
    'L0_x_state',               cell(1,N_FIELDS), ...
    'L1_running_x_state',       cell(1,N_FIELDS), ...
    'L1_x_state',               cell(1,N_FIELDS), ... 
    'L2_running_x_state',       cell(1,N_FIELDS), ...
    'L2_x_state',               cell(1,N_FIELDS), ...
    'KLD',                      cell(1,N_FIELDS), ...
    'logLikelihood',            cell(1,N_FIELDS), ...
    'DStat',                    cell(1,N_FIELDS)); 

end